class FakeAIClient:
    """
    Fake AI client used to validate the workflow without calling a real LLM.
    """

    def generate(self, prompt: str) -> str:
        return f"""
# Product Requirement Document

This is a PRD generated by the Fake AI Client.

When we integrate Ollama,
the result of this method will come from the model.

Received prompt length:

{len(prompt)} characters.
"""
